name: Deploy second brain frontend to azure VM
on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./Docker/DockerFile.fe
                push: true
                tags: lomashchoudhary/second-brain-fe:${{ github.sha }}
            
            - name: Deploy it to a VM using docker hub
              run: |
               echo "${{ secrets.PRIVATE_KEY }}" &> ~/ssh_key
               mkdir -p ~/.ssh
               cd ~/.ssh
               touch ~/.ssh/know_hosts
               echo "${{ secrets.KNOW_HOSTS }}" &> ~/.ssh/know_hosts
               chmod 700 ~/ssh_key
               ssh -o strictHostKeyChecking=no -i second-brain-backend_key_azure_root_user.pem rootUserAzure@${{secrets.VM_IP}} << EOF
               sudo docker pull lomashchoudhary/second-brain-fe:${{ github.sha }}
               sudo docker stop second-brain-fe || true
               sudo docker rm second-brain-fe || true
               sudo docker run -d --name second-brain-fe \
               -e VITE_APP_BACKEND_URL="${{ secrets.VITE_APP_BACKEND_URL }}" \
               -p 4173:4173 \
               lomashchoudhary/second-brain-fe:${{ github.sha }}
               EOF

            
            